name: Main PR Authorized User Guard

on:
  pull_request:
    branches:
      - main

jobs:
  validate-author:
    name: Main PR authorized user guard
    runs-on: ubuntu-latest

    steps:
      - name: Check PR author
        run: |
          echo "PR author: ${{ github.event.pull_request.user.login }}"

          AUTHORIZED_USERS=("RaminduA")

          IS_AUTHORIZED=false

          for USER in "${AUTHORIZED_USERS[@]}"; do
            if [ "$USER" = "${{ github.event.pull_request.user.login }}" ]; then
              IS_AUTHORIZED=true
              break
            fi
          done

          if [ "$IS_AUTHORIZED" != "true" ]; then
            echo "User '${{ github.event.pull_request.user.login }}' is not authorized to create PRs into main."
            exit 1
          fi

          echo "Authorized release PR user."
